# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=60)),
                ('flag', models.BooleanField(choices=[(0, '是'), (1, '否')], default=0, max_length=1)),
            ],
        ),
    ]
