# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='text',
            field=models.CharField(max_length=99),
        ),
    ]
