# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_auto_20170323_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informations',
            options={'verbose_name': '待办事项', 'verbose_name_plural': '待办事项'},
        ),
        migrations.AlterField(
            model_name='informations',
            name='flag',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, max_length=1, verbose_name='标记'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='text',
            field=models.CharField(max_length=99, verbose_name='事项'),
        ),
    ]
