# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_auto_20170323_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='保存日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informations',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
    ]
