# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0004_auto_20170410_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 22, 18, 19, 61267), verbose_name='保存日期'),
        ),
    ]
