# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0005_auto_20170410_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 22, 22, 56, 186544), verbose_name='保存日期'),
        ),
    ]
